# This rule is not used by the project promscale itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the autoscaling.mlop.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: promscale
    app.kubernetes.io/managed-by: kustomize
  name: inferencescaler-editor-role
rules:
- apiGroups:
  - autoscaling.mlop.io
  resources:
  - inferencescalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.mlop.io
  resources:
  - inferencescalers/status
  verbs:
  - get
