//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceScaler) DeepCopyInto(out *InferenceScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceScaler.
func (in *InferenceScaler) DeepCopy() *InferenceScaler {
	if in == nil {
		return nil
	}
	out := new(InferenceScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceScalerList) DeepCopyInto(out *InferenceScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceScalerList.
func (in *InferenceScalerList) DeepCopy() *InferenceScalerList {
	if in == nil {
		return nil
	}
	out := new(InferenceScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceScalerSpec) DeepCopyInto(out *InferenceScalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]ScalingSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(ScalingBehavior)
		(*in).DeepCopyInto(*out)
	}
	if in.Safeguards != nil {
		in, out := &in.Safeguards, &out.Safeguards
		*out = new(SafeguardsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceScalerSpec.
func (in *InferenceScalerSpec) DeepCopy() *InferenceScalerSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceScalerStatus) DeepCopyInto(out *InferenceScalerStatus) {
	*out = *in
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]ObservedSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]ReplicaRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceScalerStatus.
func (in *InferenceScalerStatus) DeepCopy() *InferenceScalerStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedSignal) DeepCopyInto(out *ObservedSignal) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedSignal.
func (in *ObservedSignal) DeepCopy() *ObservedSignal {
	if in == nil {
		return nil
	}
	out := new(ObservedSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerReplicaStrategy) DeepCopyInto(out *PerReplicaStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerReplicaStrategy.
func (in *PerReplicaStrategy) DeepCopy() *PerReplicaStrategy {
	if in == nil {
		return nil
	}
	out := new(PerReplicaStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSpec) DeepCopyInto(out *PrometheusSpec) {
	*out = *in
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSpec.
func (in *PrometheusSpec) DeepCopy() *PrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessSafeguard) DeepCopyInto(out *ReadinessSafeguard) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinReadySecondsAfterScaleUp != nil {
		in, out := &in.MinReadySecondsAfterScaleUp, &out.MinReadySecondsAfterScaleUp
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessSafeguard.
func (in *ReadinessSafeguard) DeepCopy() *ReadinessSafeguard {
	if in == nil {
		return nil
	}
	out := new(ReadinessSafeguard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaRecommendation) DeepCopyInto(out *ReplicaRecommendation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaRecommendation.
func (in *ReplicaRecommendation) DeepCopy() *ReplicaRecommendation {
	if in == nil {
		return nil
	}
	out := new(ReplicaRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafeguardsSpec) DeepCopyInto(out *SafeguardsSpec) {
	*out = *in
	in.Readiness.DeepCopyInto(&out.Readiness)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafeguardsSpec.
func (in *SafeguardsSpec) DeepCopy() *SafeguardsSpec {
	if in == nil {
		return nil
	}
	out := new(SafeguardsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDirection) DeepCopyInto(out *ScaleDirection) {
	*out = *in
	if in.MaxStep != nil {
		in, out := &in.MaxStep, &out.MaxStep
		*out = new(int32)
		**out = **in
	}
	if in.CooldownSeconds != nil {
		in, out := &in.CooldownSeconds, &out.CooldownSeconds
		*out = new(int32)
		**out = **in
	}
	if in.StabilizationWindowSeconds != nil {
		in, out := &in.StabilizationWindowSeconds, &out.StabilizationWindowSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDirection.
func (in *ScaleDirection) DeepCopy() *ScaleDirection {
	if in == nil {
		return nil
	}
	out := new(ScaleDirection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBehavior) DeepCopyInto(out *ScalingBehavior) {
	*out = *in
	if in.PollIntervalSeconds != nil {
		in, out := &in.PollIntervalSeconds, &out.PollIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	in.ScaleUp.DeepCopyInto(&out.ScaleUp)
	in.ScaleDown.DeepCopyInto(&out.ScaleDown)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBehavior.
func (in *ScalingBehavior) DeepCopy() *ScalingBehavior {
	if in == nil {
		return nil
	}
	out := new(ScalingBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSignal) DeepCopyInto(out *ScalingSignal) {
	*out = *in
	in.Strategy.DeepCopyInto(&out.Strategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSignal.
func (in *ScalingSignal) DeepCopy() *ScalingSignal {
	if in == nil {
		return nil
	}
	out := new(ScalingSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalStrategy) DeepCopyInto(out *SignalStrategy) {
	*out = *in
	if in.PerReplica != nil {
		in, out := &in.PerReplica, &out.PerReplica
		*out = new(PerReplicaStrategy)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(ThresholdStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalStrategy.
func (in *SignalStrategy) DeepCopy() *SignalStrategy {
	if in == nil {
		return nil
	}
	out := new(SignalStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdAction) DeepCopyInto(out *ThresholdAction) {
	*out = *in
	if in.ScaleUpBy != nil {
		in, out := &in.ScaleUpBy, &out.ScaleUpBy
		*out = new(int32)
		**out = **in
	}
	if in.ScaleDownBy != nil {
		in, out := &in.ScaleDownBy, &out.ScaleDownBy
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdAction.
func (in *ThresholdAction) DeepCopy() *ThresholdAction {
	if in == nil {
		return nil
	}
	out := new(ThresholdAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdStrategy) DeepCopyInto(out *ThresholdStrategy) {
	*out = *in
	if in.Above != nil {
		in, out := &in.Above, &out.Above
		*out = new(string)
		**out = **in
	}
	if in.Below != nil {
		in, out := &in.Below, &out.Below
		*out = new(string)
		**out = **in
	}
	in.Action.DeepCopyInto(&out.Action)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdStrategy.
func (in *ThresholdStrategy) DeepCopy() *ThresholdStrategy {
	if in == nil {
		return nil
	}
	out := new(ThresholdStrategy)
	in.DeepCopyInto(out)
	return out
}
